version: '3'

volumes:
  data:

services:
  sonarqube:
    build:
      context: "sonar"
    ports:
    - "9000:9000"
    links:
    - db
    environment:
    - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonar
    restart: unless-stopped

  db:
    image: postgres
    volumes:
      - data:/var/lib/postgresql
    environment:
    - POSTGRES_USER=sonar
    - POSTGRES_PASSWORD=sonar
    restart: unless-stopped
