sonarqube:
  build: "sonar"
  ports:
   - "9000:9000"
  links:
   - db
  environment:
   - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonar
  restart: unless-stopped

db:
  image: postgres
  volumes_from:
    - datadb
  environment:
   - POSTGRES_USER=sonar
   - POSTGRES_PASSWORD=sonar
  restart: unless-stopped

datadb:
  image: postgres
  volumes:
    - /var/lib/postgresql
  command: /bin/true
